# Generated by Django 6.0.6 on 2026-06-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance_to_other', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('weeks', models.IntegerField(default=18)),
                ('exam_type', models.CharField(blank=True, choices=[('exam', 'Экзамен'), ('credit', 'Зачёт')], max_length=10, null=True)),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.academicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.department')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_duration_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('lecture', 'Лекционная'), ('practice', 'Практическая'), ('lab', 'Лаборатория'), ('computer', 'Компьютерный класс'), ('hall', 'Спортивный зал'), ('online', 'Онлайн')], max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.building')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_parity', models.CharField(choices=[('even', 'Чётная неделя'), ('odd', 'Нечётная неделя'), ('both', 'Обе недели')], default='both', max_length=10)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.scheduleentry')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group_type', models.CharField(choices=[('full', 'Полная группа'), ('subgroup', 'Подгруппа'), ('stream', 'Поток'), ('mixed', 'Сборная')], max_length=20)),
                ('student_count', models.PositiveIntegerField()),
                ('academic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.academicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('academic_degree', models.CharField(blank=True, max_length=100)),
                ('academic_title', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('max_hours_per_day', models.IntegerField(default=8)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.department')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.discipline')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lessontype')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_working', models.BooleanField(default=True)),
                ('week_parity', models.CharField(choices=[('even', 'Чётная неделя'), ('odd', 'Нечётная неделя'), ('both', 'Обе недели')], default='both', max_length=10)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.discipline'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.studentgroup'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacherassignment'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='working_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.workingday'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(fields=('room', 'time_slot', 'working_day', 'week_parity'), name='unique_room_slot'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(fields=('teacher_assignment', 'time_slot', 'working_day', 'week_parity'), name='unique_teacher_slot'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(fields=('student_group', 'time_slot', 'working_day', 'week_parity'), name='unique_group_slot'),
        ),
    ]
