# Generated by Django 6.0.6 on 2026-06-10 03:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_academicgroup_building_curriculum_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(verbose_name='Время в пути (мин)')),
            ],
            options={
                'verbose_name': 'Расстояние между корпусами',
                'verbose_name_plural': 'Расстояния между корпусами',
            },
        ),
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='unique_room_slot',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='unique_teacher_slot',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='unique_group_slot',
        ),
        migrations.AlterModelOptions(
            name='academicgroup',
            options={'verbose_name': 'Академическая группа', 'verbose_name_plural': 'Академические группы'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name': 'Тип занятия', 'verbose_name_plural': 'Типы занятий'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'verbose_name': 'Учебное поручение', 'verbose_name_plural': 'Учебные поручения'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['pair_number'], 'verbose_name': 'Время пары', 'verbose_name_plural': 'Время пар'},
        ),
        migrations.AlterModelOptions(
            name='workingday',
            options={'ordering': ['date'], 'verbose_name': 'Учебный день', 'verbose_name_plural': 'Учебные дни'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='distance_to_other',
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('academic_group', 'discipline', 'semester')},
        ),
        migrations.RemoveField(
            model_name='workingday',
            name='is_holiday',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='lab_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Лабораторные часы'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='lecture_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Лекционные часы'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='practice_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Практические часы'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='hours_allocated',
            field=models.IntegerField(default=0, verbose_name='Выделено часов'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=1, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='direction',
            field=models.CharField(max_length=200, verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Шифр группы'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название/Номер корпуса'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='academic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.academicgroup', verbose_name='Академическая группа'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('exam', 'Экзамен'), ('credit', 'Зачёт'), ('none', 'Без отчетности')], max_length=10, null=True, verbose_name='Вид отчетности'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='semester',
            field=models.IntegerField(verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='year',
            field=models.IntegerField(verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='schedule.department', verbose_name='Вышестоящее подразделение'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование дисциплины'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='default_duration_minutes',
            field=models.IntegerField(verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название типа'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.building', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Вместимость (мест)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер/Имя аудитории'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Лекционная'), ('practice', 'Практическая'), ('lab', 'Лаборатория'), ('computer', 'Компьютерный класс'), ('hall', 'Спортивный зал')], max_length=20, verbose_name='Тип помещения'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.academicgroup', verbose_name='Академическая группа'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group_type',
            field=models.CharField(choices=[('full', 'Полная группа'), ('subgroup', 'Подгруппа'), ('stream', 'Поток'), ('mixed', 'Сборная')], max_length=20, verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название учебной группы'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='student_count',
            field=models.PositiveIntegerField(verbose_name='Количество обучающихся'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Учёная степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Учёное звание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.department', verbose_name='Подразделение (Кафедра)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_hours_per_day',
            field=models.IntegerField(default=8, verbose_name='Макс. часов в день'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.lessontype', verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='pair_number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Рабочий день'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='week_parity',
            field=models.CharField(choices=[('even', 'Чётная неделя'), ('odd', 'Нечётная неделя'), ('both', 'Обе недели')], default='both', max_length=10, verbose_name='Четность недели'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'discipline', 'lesson_type'), name='unique_teacher_discipline_lesson_type'),
        ),
        migrations.AddField(
            model_name='buildingdistance',
            name='from_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='schedule.building', verbose_name='От корпуса'),
        ),
        migrations.AddField(
            model_name='buildingdistance',
            name='to_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='schedule.building', verbose_name='До корпуса'),
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='replacement',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='room',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='student_group',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='teacher_assignment',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='working_day',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='hours_per_week',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='weeks',
        ),
        migrations.AddConstraint(
            model_name='buildingdistance',
            constraint=models.UniqueConstraint(fields=('from_building', 'to_building'), name='unique_building_pair'),
        ),
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
    ]
