# Generated by Django 6.0.6 on 2026-06-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_buildingdistance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('university', 'Университет'), ('school', 'Школа / Институт'), ('department', 'Департамент'), ('chair', 'Кафедра')], default='university', max_length=20, verbose_name='Тип подразделения'),
            preserve_default=False,
        ),
    ]
