# Generated by Django 6.0.6 on 2026-06-18 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_department_dept_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='Название праздника')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Семестр')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('weeks', models.PositiveSmallIntegerField(default=18, verbose_name='Количество недель')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='weeks',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Количество недель'),
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_parity', models.CharField(choices=[('even', 'Чётная неделя'), ('odd', 'Нечётная неделя'), ('both', 'Обе недели')], default='both', max_length=10)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='schedule.scheduleentry')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='schedule.room')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule.studentgroup')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule.teacherassignment')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='schedule.timeslot')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='schedule.workingday')),
            ],
            options={
                'verbose_name': 'Занятие в расписании',
                'verbose_name_plural': 'Занятия в расписании',
                'constraints': [models.UniqueConstraint(fields=('student_group', 'time_slot', 'working_day', 'week_parity'), name='unique_group_slot'), models.UniqueConstraint(fields=('teacher_assignment', 'time_slot', 'working_day', 'week_parity'), name='unique_teacher_slot'), models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'time_slot', 'working_day', 'week_parity'), name='unique_room_slot')],
            },
        ),
    ]
