# Generated by Django 6.0.6 on 2026-06-18 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_holiday_semester_curriculum_weeks_scheduleentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupAcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь учебной группы и академической группы',
                'verbose_name_plural': 'Связи учебных групп и академических групп',
            },
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='location_type',
            field=models.CharField(choices=[('room', 'Аудитория'), ('online', 'Онлайн')], default='room', max_length=10, verbose_name='Формат проведения'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='schedule.semester', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='working_days', to='schedule.semester', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='semester',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_student_groups', to='schedule.academicgroup', verbose_name='Основная академическая группа'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='week_parity',
            field=models.CharField(choices=[('even', 'Чётная неделя'), ('odd', 'Нечётная неделя'), ('both', 'Обе недели')], default='both', max_length=10, verbose_name='Чётность недели'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('academic_group', 'discipline', 'year', 'semester'), name='unique_curriculum_item'),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(fields=('semester', 'date'), name='unique_semester_date'),
        ),
        migrations.AddField(
            model_name='studentgroupacademicgroup',
            name='academic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_bindings', to='schedule.academicgroup', verbose_name='Академическая группа'),
        ),
        migrations.AddField(
            model_name='studentgroupacademicgroup',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_bindings', to='schedule.studentgroup', verbose_name='Учебная группа'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupacademicgroup',
            constraint=models.UniqueConstraint(fields=('student_group', 'academic_group'), name='unique_student_group_academic_group'),
        ),
    ]
