# Generated by Django 6.0.6 on 2026-06-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_studentgroupacademicgroup_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherassignment',
            name='unique_teacher_discipline_lesson_type',
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.curriculum', verbose_name='Учебный план (дисциплина, семестр, группа)'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Предпочтительные дни недели (номера, 0=пн...5=сб)'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='preferred_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Предпочтительное окончание занятий'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='preferred_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Предпочтительное начало занятий'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='hours_allocated',
            field=models.IntegerField(default=0, verbose_name='Выделено часов (на семестр)'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'discipline', 'lesson_type', 'curriculum'), name='unique_teacher_discipline_lesson_curriculum'),
        ),
    ]
